title: "Dr Jake Taylor"
description: ""
url: "https://astrojaket.github.io"

# Theme and Plugins
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Markdown Support
markdown: kramdown

# Defaults for Layout
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"

# SEO Settings
author: "Jake SEO"
language: "en"
social:
  name: "Jake Taylor"
  links:
    - "https://bsky.app/profile/astrojake"
    - "https://www.tiktok.com/@astrojaket"

# Sitemap Settings
sitemap:
  exclude: ['404.html']
