title: "Dr Jake Taylor"
description: "Astrophysicist at the University of Oxford studying the atmospheres of exoplanets with JWST, atmospheric retrievals and machine learning."
url: "https://www.astrojake.com"
baseurl: ""

include:
  - assets/data/mast_7d.json

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"

author:
  name: "Dr Jake Taylor"
  url: "https://www.astrojake.com/about/"

locale: "en_GB"
language: "en-GB"

social:
  name: "Dr Jake Taylor"
  links:
    - "https://www.physics.ox.ac.uk/our-people/jaketaylor"
    - "https://github.com/astrojaket"
    - "https://bsky.app/profile/astrojake.bsky.social"
    - "https://www.tiktok.com/@astrojaket"

sitemap:
  exclude:
    - "404.html"

sass:
  style: compressed
