title: "Jake Taylor"
description: "Astrophysics research, publications, and updates."
url: "https://astrojaket.github.io"
baseurl: ""
include:
  - assets/data/mast_7d.json

# Theme and plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Markdown Support
markdown: kramdown
highlighter: rouge

# Defaults for Layout
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"

# SEO Settings
author: "Jake Taylor"
language: "en"
social:
  name: "Jake Taylor"
  links:
    - "https://bsky.app/profile/astrojake"
    - "https://www.tiktok.com/@astrojaket"

# Sitemap Settings
sitemap:
  exclude:
    - "404.html"

# Sass
sass:
  style: compressed
